// GENERATED by scripts/seed/gen/_build_reading_sets.mts — do not hand-edit.
//
// Answers in the 15 new Reading Part A sets where the AUTHOR wrote that there is
// nothing else to accept ("sirf X — is ka koi doosra lafz nahi"). gate:accept-
// lists A4 requires every free-text answer to have an accept-list; these
// deliberately have none, and A4 must be able to tell that apart from an answer
// whose accept-list nobody wrote. The reason is the author's own sentence.
//
// Closed both ways by A4: an unlisted answer with no accept-list fails, and a
// listed answer that GAINS one fails too, so this cannot rot.
export const READING_SETS_SINGLE_FORM: { item: string; answer: string; why: string }[] =
[
  {
    "item": "Part A — Pneumonia acquired in the community",
    "answer": "vaccination",
    "why": "author: 'sirf vaccination — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Pneumonia acquired in the community",
    "answer": "confusion",
    "why": "author: 'sirf confusion — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Pneumonia acquired in the community",
    "answer": "help",
    "why": "author: 'sirf help — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Delirium in the older inpatient",
    "answer": "attention",
    "why": "author: 'sirf attention — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Delirium in the older inpatient",
    "answer": "December",
    "why": "author: 'sirf December — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Delirium in the older inpatient",
    "answer": "dementia",
    "why": "author: 'sirf dementia — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Delirium in the older inpatient",
    "answer": "fluctuates",
    "why": "author: 'sirf fluctuates — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Urinary catheters and infection",
    "answer": "colonisation",
    "why": "author: 'sirf colonisation — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Urinary catheters and infection",
    "answer": "inserted",
    "why": "author: 'sirf inserted — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Urinary catheters and infection",
    "answer": "reason",
    "why": "author: 'sirf reason — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Urinary catheters and infection",
    "answer": "closed",
    "why": "author: 'sirf closed — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Urinary catheters and infection",
    "answer": "antibiotic",
    "why": "author: 'sirf antibiotic — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Pain relief after surgery",
    "answer": "sedation",
    "why": "author: 'sirf sedation — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Pain relief after surgery",
    "answer": "tolerated",
    "why": "author: 'sirf tolerated — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Pain relief after surgery",
    "answer": "daily",
    "why": "author: 'sirf daily — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "weekly",
    "why": "author: 'sirf weekly — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "food",
    "why": "author: 'sirf food — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "flush",
    "why": "variant repair left no accepted alternative (source said: flushed)"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "eaten",
    "why": "author: 'sirf eaten — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "replaces",
    "why": "author: 'sirf replaces — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Malnutrition and feeding in hospital",
    "answer": "flushed",
    "why": "author: 'sirf flushed — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — A flare-up of chronic obstructive lung disease",
    "answer": "carbon dioxide",
    "why": "author: 'sirf carbon dioxide — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — A flare-up of chronic obstructive lung disease",
    "answer": "frequently",
    "why": "author: 'sirf frequently — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — A flare-up of chronic obstructive lung disease",
    "answer": "delay",
    "why": "author: 'sirf delay — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — A flare-up of chronic obstructive lung disease",
    "answer": "leaves",
    "why": "author: 'sirf leaves — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Atrial fibrillation and anticoagulation",
    "answer": "rate control",
    "why": "author: 'sirf rate control — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Atrial fibrillation and anticoagulation",
    "answer": "fix",
    "why": "author: 'sirf fix — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Atrial fibrillation and anticoagulation",
    "answer": "missed",
    "why": "author: 'sirf missed — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Seizures and prolonged convulsions",
    "answer": "restrain",
    "why": "author: 'sirf restrain — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Seizures and prolonged convulsions",
    "answer": "weakness",
    "why": "author: 'sirf weakness — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Seizures and prolonged convulsions",
    "answer": "epilepsy",
    "why": "author: 'sirf epilepsy — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Seizures and prolonged convulsions",
    "answer": "baths",
    "why": "author: 'sirf baths — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "fluid",
    "why": "author: 'sirf fluid — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "glucose",
    "why": "author: 'sirf glucose — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "litres",
    "why": "author: 'sirf litres — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "long-acting",
    "why": "author: 'sirf long-acting — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "bicarbonate",
    "why": "author: 'sirf bicarbonate — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "hourly",
    "why": "author: 'sirf hourly — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Diabetic ketoacidosis",
    "answer": "follow-up",
    "why": "author: 'sirf follow-up — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "fluid",
    "why": "author: 'sirf fluid — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "vaccination",
    "why": "author: 'sirf vaccination — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "muscle",
    "why": "author: 'sirf muscle — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "restart",
    "why": "author: 'sirf restart — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "salt",
    "why": "author: 'sirf salt — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Heart failure and fluid overload",
    "answer": "palliative",
    "why": "author: 'sirf palliative — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with a tracheostomy",
    "answer": "saline",
    "why": "author: 'sirf saline — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with a tracheostomy",
    "answer": "swallowing",
    "why": "author: 'sirf swallowing — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with a tracheostomy",
    "answer": "open",
    "why": "author: 'sirf open — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "pillows",
    "why": "author: 'sirf pillows — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "uncertainty",
    "why": "author: 'sirf uncertainty — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "stock",
    "why": "author: 'sirf stock — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "shorten",
    "why": "author: 'sirf shorten — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "forced",
    "why": "author: 'sirf forced — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Care in the last days of life",
    "answer": "ritual",
    "why": "author: 'sirf ritual — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Infectious diarrhoea on the ward",
    "answer": "formed",
    "why": "author: 'sirf formed — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Infectious diarrhoea on the ward",
    "answer": "potassium",
    "why": "author: 'sirf potassium — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Infectious diarrhoea on the ward",
    "answer": "relapse",
    "why": "author: 'sirf relapse — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with dementia in hospital",
    "answer": "delirium",
    "why": "author: 'sirf delirium — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with dementia in hospital",
    "answer": "argue",
    "why": "author: 'sirf argue — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Caring for a patient with dementia in hospital",
    "answer": "particular",
    "why": "author: 'sirf particular — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Peripheral cannulas and phlebitis",
    "answer": "pain",
    "why": "author: 'sirf pain — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Peripheral cannulas and phlebitis",
    "answer": "removed",
    "why": "author: 'sirf removed — is ka koi doosra lafz nahi'"
  },
  {
    "item": "Part A — Peripheral cannulas and phlebitis",
    "answer": "tight",
    "why": "author: 'sirf tight — is ka koi doosra lafz nahi'"
  }
];
