// Seeds original OET Speaking (role-play) items. These are PER-PROFESSION: each
// item carries a `profession`. Phase 0 ships Nursing starter content; the other
// 11 professions follow in content batches. Scenarios are original to AlmiOET —
// never copied from OET.
//
// Run: npm run seed:speaking  (needs DATABASE_URL set)
//
// 🔴 prepSeconds IS 120, NOT 60, AND THIS FILE WAS THE LAST PLACE STILL SAYING 60.
//
// OET's Speaking page states candidates get "2-3 minutes to prepare for each"
// role-play (https://occupationalenglishtest.org/test-information/speaking/ —
// read by hand on 2026-08-31; the site answers 403 to automated fetches, so an
// unattended re-check is not possible). 120 is inside that range and is a
// condition a learner may actually face; 180 would train only for the easiest
// case. 60 sat OUTSIDE the range entirely.
//
// scripts/seed/gen/speaking_*.ts was corrected to 120 on 2026-08-31 and G6 in
// scripts/gates/run.ts guards it there. This file kept 60 for all 24 items and
// nothing noticed, because G6 reads GEN_ITEMS only and the append.ts guard
// compared (taskType, profession, title) without looking at payloads. G7 now
// compares the two copies BY VALUE — see scripts/seed/divergence.ts.
//
// These items are NOT seeded; gen/ is. They are still the file a person opens
// and reads, so a wrong number here is a wrong number in the repo.

import { PrismaClient, Prisma } from "@prisma/client";
import { isDirectRun } from "./_entry";

const prisma = new PrismaClient();

export const ITEMS: Prisma.OetItemCreateManyInput[] = [
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "NURSING",
    title: "Nursing — Reassuring a patient anxious about discharge",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "patient-education",
    payload: {"setting":"Hospital ward, at the bedside, with discharge planned for this afternoon.","candidateRole":"You are the ward nurse. The patient is medically fit for discharge after treatment for community-acquired pneumonia.","patientRole":"A 68-year-old who lives alone in a first-floor flat, has been breathless at night on the ward, and has twice asked whether she could stay one more day.","patientConcern":"The patient is afraid the breathlessness will return during the night and that nobody will be there to help.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what specifically worries her about going home, and let her name it rather than guessing.\n\nAsk how the nights have been on the ward and what she does when the breathlessness comes.\n\nAcknowledge the fear and treat it as a practical problem to be solved rather than as reluctance.\n\nExplain what has improved: the observations, the oxygen levels and the chest, so the discharge has visible reasons.\n\nExplain the support arranged: the community nurse visit, the follow-up appointment and who checks on her.\n\nGo through the medication with her, including the antibiotic course, what each is for and when to take it.\n\nExplain exactly what to do if the breathlessness returns at night, in steps, including who to call at which hour.\n\nAsk practical questions about home: stairs, shopping, heating, and who has a key.\n\nOffer what can still be arranged today, including a personal alarm and a call from the ward tomorrow.\n\nAgree the plan, write it down, and check she can say back what she would do at three in the morning."},
    guidanceNote:
      "Open by drawing out the real worry before reassuring. Address the specific concern (night-time breathlessness), not a generic script. Build rapport, give clear structure, and check understanding at the end.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "NURSING",
    title: "Nursing — Supporting a patient hesitant about starting insulin",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "advice",
    payload: {"setting":"Diabetes clinic in a community health centre, a follow-up after the doctor recommended starting insulin.","candidateRole":"You are the practice nurse. The patient's type 2 diabetes is no longer controlled on maximum oral therapy and insulin has been recommended.","patientRole":"A 56-year-old delivery driver who has had type 2 diabetes for nine years, has always managed on tablets and diet, and has an HbA1c of 84 mmol/mol.","patientConcern":"The patient believes needing insulin means they have failed and that the diabetes is now severe, and fears self-injecting and losing the driving licence and the job.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask how they feel about what the doctor said last week, and give room for more than a practical answer.\n\nAsk what insulin means to them, and where that idea has come from.\n\nCorrect the sense of failure directly: explain that the pancreas changes over years regardless of what they do.\n\nExplain why insulin is being suggested now and what the current numbers mean for their eyes, kidneys and feet.\n\nExplain what starting it would actually involve: the pen, the needle size, how often, and how it is done.\n\nShow the device and let them handle it, and offer to inject saline so it stops being imaginary.\n\nAddress driving honestly: what must be reported, what the glucose testing rules are, and how other drivers manage it.\n\nExplain hypoglycaemia: what it feels like, what to carry, and what to do, so that the fear has a procedure attached.\n\nAsk what would make the first week easier, including telephone support and who else needs to know.\n\nAgree a practical next step, even if that is a further appointment rather than starting today."},
    guidanceNote:
      "Lead with open questions and let the patient voice their fears before giving facts — naming insulin as a normal next stage (not a punishment or failure) and checking understanding will land far better than launching straight into injection technique.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "MEDICINE",
    title: "Medicine — Newly diagnosed hypertension in clinic",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "advice",
    payload: {"setting":"General practice consulting room, a results appointment after three raised readings and a week of home monitoring.","candidateRole":"You are the general practitioner. The patient has stage 1 hypertension confirmed on home readings, with a ten-year cardiovascular risk above the treatment threshold.","patientRole":"A 45-year-old accountant who feels entirely well, works twelve-hour days through the tax season, drinks most evenings, has gained eight kilograms since forty, and is reluctant to start any medication.","patientConcern":"The hidden fear is that tablets mean being ill for life and becoming like their father, who had a disabling stroke despite taking many medications.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the patient understands about the readings and what they were expecting to hear today.\n\nAsk what worries them about the diagnosis, and give room for something other than the medical answer.\n\nAsk about the family history, and let them tell you about their father in their own words.\n\nExplain what the readings mean and why treatment matters in someone who feels completely well.\n\nAddress the father's story directly: what it does and does not predict for them, and what was different about that case.\n\nExplain the lifestyle measures that genuinely move the number — salt, alcohol, weight, activity — and how much each is worth.\n\nExplain the option of medication honestly, including that it is not necessarily lifelong and is reviewed.\n\nCorrect the equation between taking a tablet and being seriously ill, in their terms rather than yours.\n\nAsk what they would be willing to try first, and agree a plan they have chosen rather than accepted.\n\nArrange follow-up with a defined review point and say what would change the plan at that review."},
    guidanceNote:
      "Because the patient feels well, lead with their concerns rather than statistics. Draw out the fear about lifelong medication and the family history before recommending anything — acknowledging it openly makes shared decision-making genuine, not a script.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "MEDICINE",
    title: "Medicine — Explaining a delayed test result",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "STRETCH",
    topicTag: "advice",
    payload: {"setting":"Hospital outpatient clinic, a results appointment, where the CT scan was never booked because of an administrative error.","candidateRole":"You are the medical registrar. The patient has attended for scan results that do not exist, and you must explain why.","patientRole":"A 62-year-old retired teacher under investigation for six kilograms of unintentional weight loss, who has waited five weeks for this appointment and taken a taxi to get here.","patientConcern":"The underlying fear is that a cancer has been missed or has grown during the delay, and that nobody is taking the case seriously.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the patient is expecting from today's appointment before you say anything else.\n\nTell them plainly and early that the scan was not arranged, and do not let them discover it through hints.\n\nApologise without conditions and without immediately explaining the system that caused it.\n\nExplain honestly what went wrong, as far as you know it, and say what you do not yet know.\n\nAllow them to be angry, and do not rush to defend the department while they are speaking.\n\nExplain what has happened clinically in the meantime: the results that are available and what they show.\n\nExplain what you are doing about the scan now, including when it will happen and who will book it.\n\nExplain the safety-netting: what symptoms would mean contacting the hospital sooner, and how to do that.\n\nExplain how the error will be reported and what they can do if they wish to raise a formal concern.\n\nAgree the follow-up date, give a direct contact, and make clear who is now accountable for the pathway."},
    guidanceNote:
      "Be honest and take ownership of the error early rather than minimising it — patients forgive mistakes far more readily than evasiveness. Acknowledge the anxiety and anger as legitimate, give a concrete revised timeline, and check the patient leaves knowing exactly what happens next.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "PHARMACY",
    title: "Pharmacy — New inhaler technique and adherence",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "advice",
    payload: {"setting":"Consultation room in a community pharmacy, a new medicine service appointment for a first preventer inhaler.","candidateRole":"You are the pharmacist. The patient has been newly diagnosed with asthma and given a corticosteroid preventer inhaler alongside a reliever.","patientRole":"A 34-year-old newly started on a brown preventer inhaler in addition to a blue reliever, who has read about steroids online and intends to use it only when breathless.","patientConcern":"The patient believes inhaled steroids cause weight gain and weak bones and plans to use the preventer as a second reliever.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the patient understands about the two inhalers and what the doctor told them.\n\nAsk what they have read about steroids and what specifically concerns them.\n\nExplain the difference between the two inhalers in terms of what each does and how quickly.\n\nExplain what inhaled means: how much reaches the lung, how little reaches the rest of the body, and how that differs from steroid tablets.\n\nAddress weight gain and bone density directly with what the evidence shows for inhaled doses of this size.\n\nExplain why the preventer works only when taken every day, in terms of the inflammation that persists on good days.\n\nDemonstrate the technique, then ask them to show you, and correct what needs correcting.\n\nExplain rinsing and spitting after each dose and why it matters.\n\nAgree a daily routine anchored to something they already do, and discuss how they will notice a missed dose.\n\nAgree what good control looks like, arrange the follow-up call, and explain what to do if the reliever is needed more often."},
    guidanceNote:
      "Draw out the patient's worry about daily steroids before reassuring; acknowledge the fear, explain that inhaled doses are low and act locally, and reach a shared plan rather than simply instructing.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "PHARMACY",
    title: "Pharmacy — Declining an OTC request and GP referral",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "STRETCH",
    topicTag: "referral",
    payload: {"setting":"Community pharmacy counter, a Saturday morning, the patient asking for a product by name.","candidateRole":"You are the pharmacist. The patient is requesting an over-the-counter codeine-containing painkiller for daily headaches.","patientRole":"A 41-year-old who has bought the same product roughly every ten days for several weeks, uses it most days, and has an important week at work ahead.","patientConcern":"The patient is frustrated, fears being judged as drug-seeking, and is worried that without it they will not cope; nobody knows how often they are taking it.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask about the headaches: where, how often, how long they last, and how long this has been going on.\n\nAsk how many days a week they take a painkiller of any kind, and make an honest answer easy to give.\n\nAsk what else they have taken, including anything prescribed and anything containing caffeine.\n\nAsk about red flag features: sudden onset, waking from sleep, weakness, visual change, or a headache that is different from the usual.\n\nExplain that you cannot supply the product today, and give the reason before they have to ask for it.\n\nExplain medication-overuse headache in plain terms: how the treatment becomes the cause, and why taking more makes it worse.\n\nSay clearly that you are not accusing them of anything and that this is a common and reversible pattern.\n\nExplain what recovery involves, including that headaches typically worsen for a period before improving.\n\nRecommend what to do meanwhile, and be honest that stopping is uncomfortable rather than easy.\n\nRefer them to the GP with a specific reason, offer to write a note of what you have found, and agree a date."},
    guidanceNote:
      "Refuse the supply without sounding accusatory; normalise medication-overuse headache as a common, treatable cause, validate the patient's distress, and frame the GP referral as help rather than punishment.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "DENTISTRY",
    title: "Dentistry — Anxious patient facing a first extraction",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "advice",
    payload: {"setting":"General dental surgery, a booked appointment on a weekday morning, the patient already in the chair.","candidateRole":"You are the dentist. A non-restorable upper first molar needs extracting today and the patient has never had a tooth out.","patientRole":"A 34-year-old office worker who has never had an extraction, dreads the injection, and is worried about feeling everything and about being unfit for work the next day.","patientConcern":"The real fear is not the tooth but a painful dental experience in childhood, and a private belief that anaesthetic does not work properly on them.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the patient is expecting to happen today, and let them describe it in their own words before you correct anything.\n\nAsk directly what the worst part of it is for them, and give them room to say something other than pain.\n\nExplain what local anaesthetic does and what it does not do: that they should feel firm pressure and movement, and that pressure is not the same as pain.\n\nExplain what you will do if they do feel pain, and that more anaesthetic can be given at any point.\n\nAgree a stop signal before you start, and tell them you will honour it every time.\n\nDescribe the procedure itself in sequence and in plain language, including roughly how long it takes.\n\nExplain the aftercare: biting on the gauze, no rinsing or smoking for the rest of the day, painkillers taken before the anaesthetic wears off, and mild swelling that peaks on day two.\n\nAnswer the question about work honestly rather than optimistically, including what a desk day would realistically feel like.\n\nCheck what they have understood by asking them to tell you the plan back.\n\nAgree whether you are going ahead today or booking a longer appointment, and make either choice an acceptable one."},
    guidanceNote:
      "Slow down and check feelings before facts — naming the fear ('many people feel nervous before a first extraction') earns the trust that lets your clinical explanation actually land. Let the patient set the pace and confirm consent rather than rushing to the chair.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "DENTISTRY",
    title: "Dentistry — Parent declining fluoride for a child",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "STRETCH",
    topicTag: "advice",
    payload: {"setting":"Community dental clinic, a routine check-up appointment, the child sitting in the chair and the parent alongside.","candidateRole":"You are the dentist. A six-year-old has early decay in two lower molars and you want to apply fluoride varnish and agree a prevention plan.","patientRole":"The parent of a six-year-old, cautious about fluoride, has read online that it is harmful, and prefers natural approaches, but does want the decay stopped.","patientConcern":"The parent is not opposed to evidence so much as afraid of being judged a bad parent for the decay, and will close down if lectured.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask the parent what they have read about fluoride and where, and listen without correcting them mid-sentence.\n\nAsk what specifically worries them about it, so that you answer their concern and not the one you assume.\n\nAcknowledge that they are here, that they brought the child early, and that the decay is not a verdict on them as a parent.\n\nExplain what fluoride varnish is, how much is actually applied, how long it stays on the tooth, and what happens to the rest.\n\nExplain what the varnish is meant to achieve for these two teeth specifically, rather than in general.\n\nAsk about the child's diet and, in particular, about how often rather than how much sugar is eaten.\n\nAsk about brushing: who does it, when, how long, and whether the toothpaste is spat out rather than rinsed away.\n\nAgree the changes that the parent thinks are realistic in their household, and say them back.\n\nOffer the varnish again now that the concern has been heard, and accept a decision to think about it without withdrawing your recommendation.\n\nAgree what happens next and when you will see the child again, whatever they decide today."},
    guidanceNote:
      "Resist correcting the parent head-on; ask what they've read, validate the underlying goal (a healthy child, less sugar), and offer fluoride as one option within a shared plan. Agreeing to revisit varnish next visit can be a successful patient-centred outcome — pushing for immediate consent is not the goal.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "PHYSIOTHERAPY",
    title: "Physiotherapy — Advising a hesitant patient on early loading after ankle sprain",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "CORE",
    topicTag: "advice",
    payload: {"setting":"Outpatient physiotherapy clinic, a first appointment one week after the injury.","candidateRole":"You are the physiotherapist. The patient has a grade II lateral ankle sprain with fracture excluded on imaging.","patientRole":"A 28-year-old keen runner who has kept the foot elevated and used crutches for a week, has not put any weight through it, and has read that this should continue for six weeks.","patientConcern":"The patient fears that loading the ankle will re-tear the ligament and end their running, and is following online advice rather than what they were told.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask how the injury happened and what has been done since.\n\nAsk exactly what they have been doing: crutches, elevation, ice, and how much weight has gone through the foot.\n\nAsk what they have read and where, and take it seriously rather than dismissing it.\n\nAsk what they are most afraid of, and let running be named as the real stake.\n\nExplain what a grade II sprain is and what is happening in the ligament at one week.\n\nExplain why protected early movement and graded weight-bearing speed recovery, and what prolonged rest costs in stiffness and strength.\n\nReassure them that some discomfort with controlled loading is expected and is not damage.\n\nExplain the plan in stages: range of movement first, then weight-bearing, then balance, then running.\n\nDemonstrate the first exercises and have them do each one now.\n\nAgree the criteria for progressing rather than a fixed timetable, so they know what they are working towards.\n\nExplain what taping or a brace can add during the return to running, and for how long.\n\nAgree short-term goals for the next fortnight and what would mean contacting you sooner."},
    guidanceNote:
      "Draw out the re-injury fear before correcting the six-week belief; acknowledge the worry as reasonable rather than dismissing it, then give the graded plan.",
  },
  {
    subTest: "SPEAKING",
    taskType: "SPEAKING_ROLEPLAY",
    profession: "PHYSIOTHERAPY",
    title: "Physiotherapy — Managing a patient with chronic low back pain seeking a scan",
    prompt:
      "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.",
    difficulty: "STRETCH",
    topicTag: "advice",
    payload: {"setting":"Community musculoskeletal physiotherapy clinic, a first assessment following GP referral.","candidateRole":"You are the physiotherapist. The patient has non-specific chronic low back pain of eight months with no red flag features on assessment.","patientRole":"A 45-year-old warehouse worker convinced that an MRI scan and rest are needed, frustrated that previous appointments have offered only exercises, and now working reduced hours.","patientConcern":"The patient fears the pain means serious permanent damage and that continuing to work will end in a wheelchair, which is why proof from a scan feels essential.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they believe is causing the pain and what they think the scan would show.\n\nAsk how the pain affects work, sleep and home life, and what they have had to give up.\n\nScreen for red flags explicitly and tell them you are doing it, so the reassurance has a basis.\n\nAcknowledge that eight months of pain is a long time and that wanting an answer is reasonable.\n\nExplain what scans show in people of their age without back pain, and why the findings are often misleading.\n\nExplain why imaging is not usually helpful for this presentation, and what would change that.\n\nExplain why staying active is recommended over rest, in terms of what deconditioning does over months.\n\nAddress the wheelchair fear directly and say plainly what the evidence shows about the outlook.\n\nExplain what treatment can offer, honestly, including that it aims at function as much as at pain.\n\nAgree a graded activity and pacing plan, with something specific to do this week.\n\nAgree what would prompt review or referral, so the door is not closed on further investigation."},
    guidanceNote:
      "Validate the fear of permanent damage before explaining why a scan would not change management; offer the staying-active message as protective, not dismissive, and co-agree one concrete step.",
  },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "DIETETICS", title: "Dietetics — Newly diagnosed coeliac disease advice", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "FOUNDATION", topicTag: "advice", payload: {"setting":"Outpatient dietetics clinic at a general hospital, the first dietetic appointment after diagnosis.","candidateRole":"You are the dietitian. The patient has biopsy-confirmed coeliac disease and has had no dietary advice so far.","patientRole":"A 29-year-old who cooks for friends most weekends, eats out several times a week, works as a chef in a busy restaurant kitchen, and has had symptoms for two years.","patientConcern":"The patient is privately worried that a gluten-free diet ends their social life and their job, and will only relax if that is addressed rather than the label reading.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they already understand about coeliac disease and about gluten.\n\nAsk what they eat on an ordinary day and what their work involves.\n\nAsk what worries them most about the diagnosis, and give room for the social and work answer.\n\nExplain what coeliac disease does to the bowel and why the diet must be strict and lifelong.\n\nExplain which everyday foods contain gluten, including the ones people do not expect.\n\nExplain cross-contamination in practical terms: the toaster, the chopping board, the pasta water, and the shared butter.\n\nAddress the kitchen at work specifically, since that is a daily exposure risk and a legal matter for the employer.\n\nExplain label reading, the crossed-grain symbol, and what gluten-free means legally.\n\nDiscuss eating out honestly: what is manageable, what to ask, and which situations are genuinely difficult.\n\nExplain the prescribable staples, the coeliac society, and the family screening question.\n\nExplain what improvement to expect and over what period, so the first few weeks are not judged too soon.\n\nAgree one or two manageable changes to start with, and arrange the follow-up and repeat bloods."}, guidanceNote: "Check understanding before launching into food lists, and draw out the social worry — telling them gluten-free dining is possible, with concrete tactics, matters more than reciting every banned grain." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "DIETETICS", title: "Dietetics — Renal diet & phosphate concern in CKD", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Renal dietetics clinic at a kidney care unit, a routine review after recent blood tests.","candidateRole":"You are the dietitian. The patient has stage 4 chronic kidney disease and a raised serum phosphate on the latest bloods.","patientRole":"A 61-year-old not yet on dialysis who feels entirely well, drinks two litres of cola daily, eats processed meats, and takes the binders only when he remembers.","patientConcern":"The patient feels completely well, believes the diet change is pointless and restrictive, and fears losing every food he enjoys.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what he eats and drinks on an ordinary day, with particular attention to dairy, processed meat, cola and nuts.\n\nAsk what he understands about the blood results and what he has been told before.\n\nAsk how he takes the phosphate binders and when, since timing is usually the problem rather than the dose.\n\nExplain what phosphate is and where it comes from in the diet.\n\nExplain why controlling it matters, in terms of bones and blood vessels over years, rather than symptoms today.\n\nAddress directly the belief that feeling well means nothing is wrong.\n\nExplain the difference between natural phosphate in food and the additives in processed products, which are absorbed far more.\n\nShow him how to spot phosphate additives on a label, using something he actually buys.\n\nSuggest swaps that keep the foods he likes where possible, rather than a list of prohibitions.\n\nExplain how and when the binders must be taken with meals to work at all.\n\nAgree three realistic changes, and arrange the follow-up with repeat bloods."}, guidanceNote: "Acknowledge that feeling well makes the advice hard to accept, and frame phosphate control as protecting bones and heart for the future — agree just one or two swaps rather than overwhelming the patient with a long forbidden list." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "OCCUPATIONAL_THERAPY", title: "Occupational Therapy — Equipment & home adaptation advice", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Community occupational therapy home visit, following two falls in the bathroom.","candidateRole":"You are the occupational therapist recommending grab rails, a shower seat and a raised toilet seat after a home assessment.","patientRole":"A 78-year-old retired farmer with osteoarthritis who has fallen twice getting out of the bath, lives alone, and is reluctant to have the house look like a hospital.","patientConcern":"The patient fears that accepting equipment is the first step towards losing the house and being moved into residential care.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask about the two falls: what happened each time, and whether anyone knew.\n\nAsk how they manage washing now, and what they have already changed themselves.\n\nAsk what they think about equipment, and let the objection be stated fully.\n\nAcknowledge the pride and the appearance concern rather than treating either as trivial.\n\nExplain what you observed in the bathroom and why those particular movements are the risk.\n\nExplain what a fractured hip at their age would actually mean, plainly and without threat.\n\nAddress the care home fear directly, and explain that equipment is what keeps people at home.\n\nExplain what the equipment looks like now, and show photographs rather than describing it.\n\nOffer the smallest acceptable starting point, such as one rail rather than the full list.\n\nDiscuss what neighbours would actually notice, and let them decide what goes where.\n\nExplain how the equipment is provided and whether it can be removed later if unwanted.\n\nAgree a first step they are willing to try, arrange the fitting, and set a review after it."}, guidanceNote: "Lead with empathy and frame equipment as protecting independence, not signalling decline — uncover the unspoken fear of losing the home before pushing any single recommendation, and negotiate one acceptable first step." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "OCCUPATIONAL_THERAPY", title: "Occupational Therapy — Mental-health OT: graded return to routine", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Community mental health team clinic, an appointment for activity scheduling.","candidateRole":"You are the occupational therapist introducing graded activity scheduling to rebuild daily structure and a return to part-time study.","patientRole":"A 26-year-old recovering from a depressive episode, sleeping until midday, out of contact with friends, and suspended from a university course they want to resume.","patientConcern":"The patient fears that committing to goals will lead to disappointing their family again if they cannot keep up, so attempting nothing feels safer.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what a typical day looks like now, from waking to going to bed.\n\nAsk what they used to do that they valued, and what they miss most.\n\nAsk what they think would happen if they set a goal and did not manage it.\n\nAcknowledge that attempting nothing protects them from failing, and name that plainly rather than arguing with it.\n\nExplain the relationship between activity, mood and motivation, and why waiting to feel like it does not work.\n\nExplain graded activity scheduling and why the first steps must be almost too easy.\n\nAgree two small, achievable goals for the coming week, chosen by them and specific about when.\n\nBuild in what happens if a goal is not met, so the plan survives a bad week.\n\nDiscuss the family expectations and what could be said to them about the pace.\n\nDiscuss the return to study as a later stage with its own steps, so it is not the first one.\n\nAgree how the week will be recorded, and arrange the next appointment."}, guidanceNote: "Keep goals genuinely small and patient-led — in mental-health OT the therapeutic value is in achievable graded steps; validate the fear of failure rather than over-promising, and let the patient choose the activities that matter to them." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "OPTOMETRY", title: "Optometry — Explaining a cataract referral to an anxious patient", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Community optometry practice consulting room, during a routine sight test the patient booked for new glasses.","candidateRole":"You are the optometrist. A visually significant right cataract has reduced acuity to 6/18 with glare difficulty at night, and referral is indicated.","patientRole":"A 71-year-old who came in expecting stronger glasses, is alarmed by the word surgery, and is the sole carer for a housebound spouse at home.","patientConcern":"The core fear is losing independence and being unable to care for the spouse during recovery, and consent will not come until that is addressed.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they have noticed: reading, television, driving at night, and glare from headlights.\n\nAsk what the vision problem is stopping them doing, including anything to do with caring at home.\n\nExplain what a cataract is in plain language and why it is not something glasses can correct.\n\nShow them today's measurements against last year's, so the change is visible rather than asserted.\n\nExplain what the surgery involves at a basic level: day case, usually local anaesthetic, and how long it takes.\n\nAddress the anaesthetic fear specifically, and correct the assumption of a general anaesthetic.\n\nBe honest about risk without overstating it, and give a figure rather than the word small.\n\nExplain the recovery realistically: what they can do the next day, the drop regimen, and the restrictions.\n\nAsk directly about caring for their spouse during that fortnight, and discuss what support could be arranged.\n\nExplain that the second eye can be considered separately and later if it becomes troublesome.\n\nAgree the referral, explain what the hospital appointment will involve, and confirm they can change their mind."}, guidanceNote: "Avoid jargon like 'phacoemulsification'; check understanding frequently. The hidden concern is the caregiving role, so explore the patient's home situation rather than only the medical facts — addressing it is what unlocks agreement." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "OPTOMETRY", title: "Optometry — Sudden visual change and possible retinal detachment", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Optometry practice, an emergency appointment arranged by telephone this morning.","candidateRole":"You are the optometrist. Examination raises strong suspicion of a retinal detachment in the left eye requiring hospital assessment today.","patientRole":"A 55-year-old high myope with a shower of new floaters and flashes since yesterday and a grey curtain now across the lower field, who is due at a family wedding this afternoon.","patientConcern":"The hidden concern is letting the family down at the wedding, and they will not agree to go now until they hear plainly what delay costs.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask when the floaters and flashes began and when the curtain appeared, as precisely as possible.\n\nAsk whether the central vision is still clear, since this determines the urgency of the surgery.\n\nExplain what you have found on examination, in lay terms, without softening it into vagueness.\n\nExplain what may be happening to the retina, using a simple description of the layer lifting away.\n\nSay plainly that this needs assessment today and not next week, and give the reason before they argue.\n\nExplain what delay costs specifically: that once the centre detaches, the vision that is lost does not fully return.\n\nAddress the wedding directly rather than treating it as an obstacle, and acknowledge what missing it means.\n\nExplain what the hospital will do, roughly how long it takes, and that surgery may not be today.\n\nAdvise on what to do meanwhile: no driving, minimal head movement, and how to travel.\n\nMake the referral now, confirm who is taking them and how, and check they have the details in writing."}, guidanceNote: "Balance honesty about the sight-threatening risk with calm reassurance — do not minimise to placate the patient. Acknowledge the wedding explicitly; naming the genuine trade-off (a few hours now versus permanent vision loss) is usually what secures agreement to attend today." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "PODIATRY", title: "Podiatry — Advising an anxious patient at risk of foot ulceration", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Community podiatry clinic, an annual diabetic foot review appointment.","candidateRole":"You are the podiatrist. The patient has type 2 diabetes with loss of protective sensation and dry, fissured heel skin, placing them at increased risk of ulceration.","patientRole":"A 58-year-old with type 2 diabetes for nine years who says the feet are fine because nothing hurts, walks barefoot at home, and cuts their own nails.","patientConcern":"The patient secretly fears that foot problems lead to amputation as happened to a relative, so dismisses the risk rather than think about it.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they have noticed about their feet and what they currently do for them.\n\nAsk about footwear at home and outside, and about who cuts the nails.\n\nDemonstrate the monofilament test with them watching, so the loss of sensation is something they experience rather than are told.\n\nExplain in plain terms why an absence of pain does not mean the feet are safe, using what they have just seen.\n\nAsk about the relative's amputation and let the fear surface, since it is driving the avoidance.\n\nExplain honestly what leads to amputation and, more importantly, what interrupts that path.\n\nExplain what today's findings mean for their risk category and what changes it.\n\nAgree a daily routine: checking the soles with a mirror, between the toes, and moisturising while avoiding the toe webs.\n\nAdvise on footwear, on never walking barefoot, and on checking shoes before putting them on.\n\nExplain what counts as urgent: any break in the skin, redness, swelling or discharge, and who to call the same day.\n\nCheck understanding by asking them to describe the routine back, and arrange the review interval."}, guidanceNote: "Don't lecture — draw out why the patient thinks their feet are fine, then connect prevention to their hidden fear. Avoid the word 'amputation' unless the patient raises it." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "PODIATRY", title: "Podiatry — Explaining orthotics for biomechanical heel pain", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Private musculoskeletal podiatry clinic, following a biomechanical assessment and gait analysis.","candidateRole":"You are the podiatrist. You have diagnosed plantar heel pain related to overpronation and are recommending custom orthoses alongside stretching and load management.","patientRole":"A 41-year-old recreational runner with several months of sharp morning heel pain, who wants a quick fix and is openly sceptical about the cost of custom devices.","patientConcern":"The patient suspects orthoses are an expensive permanent crutch that will weaken the feet and stop them running, and wonders whether this is simply a way of selling a product.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask about the pain: first steps in the morning, through a run, and afterwards.\n\nAsk about training: distance, surfaces, footwear age, and any recent change.\n\nExplain what you found on the assessment, showing them the gait findings rather than describing them.\n\nExplain how the mechanics relate to the heel pain, in terms of load rather than of a fault to be fixed.\n\nAddress the scepticism about selling directly, and say what you would advise if you stocked nothing.\n\nExplain what an orthosis does and, importantly, what it does not do, including the weakening belief.\n\nExplain why the orthosis is one part of a plan alongside stretching and load management, and what each contributes.\n\nExplain the realistic timeframe for improvement, so a device is not judged after a fortnight.\n\nSet out the costs honestly, including what a prefabricated device would and would not achieve.\n\nExplain what would happen if they chose not to have orthoses, so declining is a real option.\n\nAgree a plan, with a review point at which the decision can be revisited."}, guidanceNote: "Acknowledge the cost and 'do I really need this' scepticism openly rather than glossing over it; frame orthoses as one temporary part of a plan, not a lifelong dependency, and tie advice back to returning to running." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "RADIOGRAPHY", title: "Radiography — MRI claustrophobia and cooperation", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"MRI suite in a hospital imaging department, immediately before a scheduled lumbar spine scan.","candidateRole":"You are the radiographer about to perform an MRI of the lumbar spine on a patient who has become visibly anxious in the waiting area.","patientRole":"A 44-year-old who has never had an MRI, has been in the waiting room for forty minutes, and asked the receptionist how wide the scanner is.","patientConcern":"The patient is terrified of panicking and being trapped, and is too embarrassed to say so unless gently invited.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask how they are feeling about the scan, and give an opening for an answer they may find embarrassing.\n\nAsk whether anything similar has been difficult before, such as lifts or crowded places.\n\nAcknowledge the fear without dismissing it, and say that it is one of the commonest reasons scans are abandoned.\n\nExplain what the scan involves in plain terms: the tunnel, how far in they go, the noise, the stillness and the duration.\n\nBe honest that the space is enclosed rather than promising it is open.\n\nExplain the safety points: no radiation, and that you are watching and listening throughout.\n\nOffer the concrete coping options: the call buzzer, headphones and music, a mirror, feet-first positioning where possible.\n\nOffer a support person in the room and a planned break partway through.\n\nLet them hold the buzzer and test it, and lie on the table before committing to the scan.\n\nExplain what happens if they need to stop, and that stopping is a normal outcome rather than a failure.\n\nGain their willingness to proceed, and agree exactly what you will do if they signal."}, guidanceNote: "Don't over-reassure or rush to the buzzer. Name the fear out loud first — 'a lot of people feel closed in' — then offer the practical controls. Being honest that it IS a snug tunnel builds more trust than pretending it's roomy." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "RADIOGRAPHY", title: "Radiography — Radiation dose concern for paediatric CT", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "STRETCH", topicTag: "advice", payload: {"setting":"CT department, the child on the trolley from the emergency department, the parent standing beside it.","candidateRole":"You are the radiographer preparing to perform a non-contrast head CT on a six-year-old following a fall from playground equipment.","patientRole":"The parent of the child, who has read online that CT scans cause cancer, and is asking whether the scan can be avoided or delayed.","patientConcern":"The parent fears they are consenting to something that could give their child cancer later, and wants to know whether it is truly necessary.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the emergency department team has explained about why the scan was requested.\n\nAsk what they have read and what specifically concerns them.\n\nExplain why the scan has been requested: the injury it is looking for and why it cannot be seen any other way.\n\nExplain that the decision was made because the clinical benefit outweighs the risk in this particular case.\n\nBe honest that CT uses X-rays and that the dose is higher than a plain film, without minimising it.\n\nExplain the measures that reduce the dose: child-sized settings, scanning only the head, and a single acquisition.\n\nAddress the cancer question proportionately, giving a sense of the size of the risk rather than dismissing it.\n\nExplain what the risk of missing a significant head injury would be, so both sides of the decision are visible.\n\nExplain practically what will happen: how quick it is, staying still, and any immobilisation.\n\nExplain whether the parent may stay in the room, and what protection they would be given.\n\nAnswer any remaining questions, gain consent to proceed, and offer to fetch the referring doctor if they wish."}, guidanceNote: "Resist saying 'it's completely safe' — that's dishonest and parents see through it. Put the small risk next to the real risk of a missed bleed, explain dose-reduction and ALARA in plain words, and confirm a doctor judged it necessary. Validate the worry rather than correcting the internet." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "SPEECH_PATHOLOGY", title: "Speech Pathology — Voice disorder in a teacher", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Outpatient voice clinic at a community health centre, following laryngoscopy by the ENT team.","candidateRole":"You are the speech pathologist. Laryngoscopy showed bilateral vocal fold nodules with no sinister features, and you are explaining the diagnosis and starting therapy.","patientRole":"A 41-year-old full-time secondary school teacher whose voice has been rough and tired for four months, worse by the afternoon, who drinks a lot of coffee and shouts over noisy classes.","patientConcern":"The patient is terrified the diagnosis means cancer and that they may have to give up teaching, and cannot engage with advice until both are addressed.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they have been told so far and what they understood from the ENT appointment.\n\nAsk what they are most worried about, and let the cancer fear be named.\n\nSay clearly and early that the nodules are benign and that nothing sinister was seen.\n\nAddress the teaching question directly and explain that giving up the job is not the recommendation.\n\nExplain what nodules are, how they form, and why they are common in people who use their voice heavily.\n\nConnect them to the specific habits described: shouting over noise, throat clearing and low fluid intake.\n\nExplain that voice therapy resolves most nodules without surgery, and how long that typically takes.\n\nNegotiate two or three practical changes: hydration, an alternative to throat clearing, and gaining attention without shouting.\n\nDiscuss classroom amplification and what occupational health could arrange.\n\nTeach one voice technique now and have them try it, so therapy is not only advice.\n\nExplain what would mean returning to ENT rather than continuing with therapy.\n\nCheck understanding, agree the therapy schedule, and set the review point."}, guidanceNote: "Resist launching straight into vocal hygiene tips. Surface and dismantle the cancer fear and the fear of losing their job first; only then will advice land. Use everyday words, not 'benign mucosal lesions'." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "SPEECH_PATHOLOGY", title: "Speech Pathology — Parent of a child who stammers", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Paediatric speech and language clinic, a first appointment following a health visitor referral.","candidateRole":"You are the speech pathologist meeting the parent of a four-year-old who has stammered for five months.","patientRole":"The parent of a four-year-old with word and sound repetitions, occasional blocks and some facial tension, who has been correcting the child and finishing sentences.","patientConcern":"The parent feels overwhelming guilt that their own correcting caused the stammer, and will not absorb any advice until that is addressed warmly and directly.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what the parent has noticed, when it started, and whether it varies from day to day.\n\nAsk what they have tried and what they were told to do by others.\n\nAsk what they think caused it, and let the guilt be spoken rather than inferred.\n\nAddress the guilt directly and warmly: explain that parents do not cause stammering, and say it plainly.\n\nExplain what is known about why stammering starts at this age, and about natural recovery.\n\nExplain why monitoring matters despite the good odds, and what raises or lowers those odds.\n\nGive two or three interaction strategies: slowing your own speech, pausing before replying, and reducing questions.\n\nExplain clearly what not to do: finishing sentences, telling the child to slow down or take a breath.\n\nAnswer the question about lifelong stammering honestly rather than reassuringly.\n\nExplain when therapy would step up and what that would involve.\n\nExplain what to do when the child becomes frustrated or comments on their own speech.\n\nAgree a review in a set timeframe, and give safety-net advice about what would prompt earlier contact."}, guidanceNote: "The single highest-impact move is to name and lift the parent's guilt early — stammering is neurological/developmental, not caused by correction. Give only a few concrete strategies; overloading an anxious parent reduces what they retain." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "VETERINARY_SCIENCE", title: "Veterinary Science — Discussing a newly diagnosed diabetic cat", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Veterinary consulting room at a small-animal practice, a results appointment after blood and urine tests.","candidateRole":"You are the veterinarian. You have diagnosed diabetes mellitus in a nine-year-old cat and need to agree home management and monitoring.","patientRole":"The owner of 'Biscuit', a nine-year-old overweight cat, anxious, who has never given an injection and has gone quiet since the word insulin was used.","patientConcern":"The owner is terrified of hurting the cat with the needle and is quietly considering euthanasia because they fear they cannot cope with lifelong injections.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they have noticed at home and what they understood from the earlier appointment.\n\nExplain what diabetes means for the cat, in plain terms, and what happens without treatment.\n\nAsk what worries them about managing it at home, and give real space for the answer.\n\nNotice the hesitation and ask gently whether they are wondering if this is treatable at all, so the euthanasia thought can be spoken.\n\nAddress that directly: explain what treatment actually asks of them day to day, and that many cats do well.\n\nExplain the insulin: how small the needle is, and that most cats barely notice it.\n\nDemonstrate the injection and have the owner do one before leaving the room.\n\nExplain the dietary change and why weight loss matters, including the possibility of remission.\n\nExplain the warning signs of low blood glucose and exactly what to do and when to call.\n\nExplain the monitoring plan, including glucose curves and how often rechecks are needed.\n\nAgree a starting plan, arrange a nurse appointment in two days, and give a number for questions."}, guidanceNote: "Don't rush into the injection technique; check the owner's confidence first and name their fear gently, because an owner who feels incapable may decline treatment that is actually very achievable." },
  { subTest: "SPEAKING", taskType: "SPEAKING_ROLEPLAY", profession: "VETERINARY_SCIENCE", title: "Veterinary Science — Vaccination hesitancy in a new puppy", prompt: "Read your role-play card. You have a short time to prepare, then carry out the consultation. Speak your part aloud.", difficulty: "CORE", topicTag: "advice", payload: {"setting":"Veterinary consulting room during a first puppy health check.","candidateRole":"You are the veterinarian. The owner is reluctant to start the core vaccination course for a healthy nine-week-old puppy.","patientRole":"The owner of 'Rocket', a nine-week-old crossbreed, who has read online that vaccines cause harm, wants to delay or skip them, and expects an argument.","patientConcern":"The real worry is that a friend's dog became unwell after a vaccination, and the owner feels guilt-tripped by clinics and wants to feel respected and in control.","prepSeconds":180,"speakSeconds":300,"candidateCard":"Ask what they have read and where, and let them tell you the whole of it.\n\nAsk whether anything has happened to a dog they know, since a personal story usually sits underneath.\n\nAcknowledge that they are asking because they want to protect the puppy, and say so plainly.\n\nExplain which diseases the core vaccines prevent and what those diseases actually do to a puppy.\n\nExplain the real rate of side effects, what a normal reaction looks like, and how rare a serious one is.\n\nAddress the friend's dog honestly rather than dismissing the account.\n\nExplain the socialisation window and why delay creates a different risk, in behaviour as well as infection.\n\nExplain what an unvaccinated puppy cannot safely do, including classes, parks and boarding.\n\nOffer the schedule and explain what each visit covers, so the plan is visible rather than open-ended.\n\nMake clear that the decision is theirs, and that you will continue to care for the puppy either way.\n\nAgree a plan they are comfortable with, even if it is one vaccine today, and arrange the next visit."}, guidanceNote: "Avoid dismissing the online claims outright; validate the owner's protective intent first, then offer clear evidence, so the conversation stays collaborative rather than confrontational." },
];

async function main() {
  const res = await prisma.oetItem.createMany({ data: ITEMS });
  console.log(`Seeded ${res.count} Speaking item(s).`);
}

if (isDirectRun(import.meta.url)) {
  main()
    .catch((e) => {
      console.error(e);
      process.exitCode = 1;
    })
    .finally(() => prisma.$disconnect());
}
