-- Two nullable columns so CODE never has to read a human-facing title.
--
-- Before this, src/lib/oet/accept-lists.ts was keyed by the full item title and
-- src/lib/oet/session.ts parsed "OET Form N · " out of the title with a regex.
-- Renaming an item would therefore have killed the accept-list overlay silently
-- (a learner's correct alternative answer marked wrong, no gate red) and stopped
-- forms being recognised at all.
--
-- EXPAND ONLY. Both columns are nullable and no existing column is altered, so
-- the deployment running now keeps working unchanged: it reads neither.
-- Backfill is a separate, guarded step, and it never rewrites a value that is
-- already set -- slug and form are written once and are then immutable.
--
-- Generated by `prisma migrate diff` against a throwaway shadow database, not
-- typed by hand.
ALTER TABLE "OetItem" ADD COLUMN     "form" TEXT,
ADD COLUMN     "slug" TEXT;

CREATE UNIQUE INDEX "OetItem_slug_key" ON "OetItem"("slug");
